"""
Configuration package — exposes all runtime settings.
"""
from .settings import (
    API_KEY,
    API_BASE,
    MODEL_NAME,
    MM_API_KEY,
    MM_API_BASE,
    MM_MODEL_NAME,
    EMBEDDING_MODEL_DIR,
    EMBED_MODEL,
    INPUT_PDF_PATH,
    CACHE_PATH,
    WORKING_DIR,
    OUTPUT_DIR,
    MMKG_NAME,
    ENTITY_EXTRACT_MAX_GLEANING,
    ENTITY_SUMMARY_MAX_TOKENS,
    SUMMARY_CONTEXT_MAX_TOKENS,
    USE_MINERU,
    QueryParam,
    RETRIEVAL_THRESHOLD,
)

__all__ = [
    "API_KEY", "API_BASE", "MODEL_NAME",
    "MM_API_KEY", "MM_API_BASE", "MM_MODEL_NAME",
    "EMBEDDING_MODEL_DIR", "EMBED_MODEL",
    "INPUT_PDF_PATH", "CACHE_PATH", "WORKING_DIR", "OUTPUT_DIR", "MMKG_NAME",
    "ENTITY_EXTRACT_MAX_GLEANING", "ENTITY_SUMMARY_MAX_TOKENS",
    "SUMMARY_CONTEXT_MAX_TOKENS", "USE_MINERU",
    "QueryParam", "RETRIEVAL_THRESHOLD",
]
